name: NestJs-Devops

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.pkg.github.com -u thorinlotr4 --password-stdin
